sudo: required
git:
  depth: 1
common_sources: &1
- ubuntu-toolchain-r-test
language: cpp
matrix:
  include:
  - os: osx
    osx_image: xcode10.3
    python:
      - "3.7"
    env:
      - MATRIX_EVAL="CC=clang && CXX=clang++ && PYTHON=python3.7"
before_install:
- eval "${MATRIX_EVAL}"
- echo $CXX
- echo $PYTHON
- sysctl -n hw.ncpu
- pwd
- cd $TRAVIS_BUILD_DIR
- mkdir taichi-llvm
- cd taichi-llvm
- wget https://github.com/yuanming-hu/taichi_assets/releases/download/llvm8/taichi-llvm-8.0.1.zip
- unzip taichi-llvm-8.0.1.zip
- export PATH=$TRAVIS_BUILD_DIR/taichi-llvm/bin/:$PATH
- ls $TRAVIS_BUILD_DIR/taichi-llvm/bin/
- echo $PATH
- cd ..
- llvm-config --version

script:
- cd $TRAVIS_BUILD_DIR
- $PYTHON dev_setup.py ci
- export TAICHI_REPO_DIR=$TRAVIS_BUILD_DIR
- export PYTHONPATH=$TAICHI_REPO_DIR/python
- export PATH=$TAICHI_REPO_DIR/bin:$PATH
- ti test
- cd python && $PYTHON build.py upload

env:
  global:
    secure: ZfG1FCWsSFSkeHtwfdHy2wR+nAq/IIFyHyTsFIVjUQdui5k6P3szXCkVonabtmZVccZF+8BXjedzwUfGw6cDY8DzzbBPC+rx4XxxuCh3ueCNfhyz+BmsnOMk20U5yBpiwHDmGSiO9jt0Tw4gPNhk/GegNT21f8nJyYzOjH4IONAby0AXDf35R7pFE3LlPEC/TsCoWEEY5/U7r8N1UJChoK3m2rGsK3TVKLY1UQYT94Ytg2a3IgjneEybQB73823K9uIS2CXM77rWJWcjhM9lDBqOc+2MoWdhVgpFst90s+8sjpjGMbMBQYz089sP6FrvGm3kYlWQ9LQ/eVqSVIstNTf176mxA1vyqkLDcuYZ/VcR+P0hTLgEo4kURy+ghXOHcDGhZW5mSXsTI5rq2xQYs6zqnc+MCIJQTOqytMPVc04to/Y5q2dLqrByZvkqeGUafa3bS8bgBr7SjAjwW3xjnWFQc2QMWHLKFP/q7eUnr6jeY4R/YpKdjIf2v+Qs54toAOqQl5Enf7+lYE+iPjU9UmHu/LliyEfIKkVWjajpRFBaF7jQMhsGby+6MDxomZdzKlJpwsfisBLh1HOq65N0erLVXMtqsy0eMxX9zBoUqcANnb0kj8MY/GdkUdZnx09yyXiQU8N+7BSETOIRxriVVGRjhcefyyaeyn5yS7oZ/kY=
