#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.{build}-{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017
clone_folder: C:\repos\taichi

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: x64
configuration: Release

build_script:
  - cd C:\repos\taichi
  - C:\Python36-x64\python.exe install.py ci
#- 7z a C:\repos\taichi\taichi_bin.zip %TAICHI_ROOT_DIR%/taichi/runtimes/*.dll %TAICHI_ROOT_DIR%/taichi/runtimes/Release/taichi_core.dll

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: taichi\taichi_bin.zip
    name: 'taichi-win-x86_64'
