#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.{build}-{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017
clone_folder: C:\taichi

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: x64
configuration: Release

environment:
  matrix:
    - PYTHON: C:\Python36-x64\python.exe
    - PYTHON: C:\Python37-x64\python.exe
    - PYTHON: C:\Python38-x64\python.exe

skip_commits:
  files:
    - '*.md'
    - '*.rst'
    - docs
    - benchmarks
    - examples
    - misc
    - '.*'

cache:
  - build -> CMakeLists.txt, cmake/*

build_script:
  - set TAICHI_REPO_DIR=C:\taichi
  - "%PYTHON% %TAICHI_REPO_DIR%/misc/appveyor_filter.py || appveyor exit 0"
  - cd C:\
  - curl --retry 10 --retry-delay 5 https://github.com/yuanming-hu/taichi_assets/releases/download/llvm8/taichi-llvm-8.0.1-msvc2017.zip -LO
  - 7z x taichi-llvm-8.0.1-msvc2017.zip -otaichi_llvm
  - curl --retry 10 --retry-delay 5 https://github.com/yuanming-hu/taichi_assets/releases/download/llvm8/clang-7.0.1-win.zip -LO
  - "echo \"%APPVEYOR_REPO_COMMIT_MESSAGE%\" | grep '^\\[format\\]' && curl http://kun.csail.mit.edu:31415/%APPVEYOR_PULL_REQUEST_NUMBER% -LO || true"
  - 7z x clang-7.0.1-win.zip -otaichi_clang
  - set PATH=C:\taichi_llvm\bin;%PATH%;
  - set PATH=C:\taichi_clang\bin;%PATH%
  - set PYTHONPATH=%TAICHI_REPO_DIR%/python
  - set PATH=%TAICHI_REPO_DIR%\bin;%PATH%
  - clang --version
  - cd C:\taichi
  - "%PYTHON% misc/ci_setup.py ci"
  - mkdir build
  - cd build
  - cmake .. -G"Visual Studio 15 2017 Win64" -DPYTHON_EXECUTABLE="%PYTHON%" -DLLVM_DIR="C:\taichi_llvm\lib\cmake\llvm"
  - msbuild /p:Configuration=RelWithDebInfo /p:Platform=x64 /m taichi.sln
  - cd ..
  - '%PYTHON% -c "import taichi"'
  - "%PYTHON% examples/laplace.py"
  - "%PYTHON% bin/taichi test -vr2 -t2"
  - "cd python && %PYTHON% build.py try_upload"
