name: Land ghstack PRs
on:
  repository_dispatch:
    types: [land-command]

jobs:
  ghstack_land:
    name: ghstack Land
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GARDENER_PAT }}
        fetch-depth: '0'
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Check Current CI Status
      run: |
        pip install requests ghstack
        .github/workflows/scripts/ghstack-perm-check.py
      env:
        GITHUB_TOKEN: ${{ secrets.GARDENER_PAT }}
    - name: Land It!
      run: |
        git config --global user.email "taichi-gardener@taichi.graphics"
        git config --global user.name "Taichi Gardener"
        cat <<EOF > ~/.ghstackrc
        [ghstack]
        github_url = github.com
        github_oauth = $GITHUB_TOKEN
        github_username = taichi-gardener
        remote_name = origin
        EOF
        ghstack land "${{ github.event.client_payload.pull_request.html_url }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GARDENER_PAT }}
